### ISSUE TITLE
TrdEvents: Published events should stay published after each import

### ISSUE THREAD

**Issue by annakastet** [Studentmediene/Barteguiden#87]

**Comment by andreasdri** [comment]
Are you sure that this is an issue? This works in production now I think.

**Comment by annakastet** [comment]
It seems to be an issue locally, but feel free to close it if it's not one in production.

**Comment by andreasdri** [comment]
Ah, it might be an issue. `isPublished` is set to false in `trdevents.js` and might override it. We have to remove this. The field defaults to false if it is not present anyway.
